name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install Latex
        run: sudo apt-get install texlive-full texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - name: Install latexmk
        run: sudo apt-get install latexmk && sudo apt install texlive-xetex
      - name: Install Fira Sans
        run: cd /tmp
          wget https://github.com/mozilla/Fira/archive/4.202.zip
          unzip 4.202.zip
          font_dir="$HOME/Library/Fonts"
          mkdir -p $font_dir
          cp Fira-4.202/otf/* $font_dir/
      - name: Compile
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: Download Artifacts
          path: thesis.pdf
