name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Configure container
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip fontconfig
      - name: Install Fira Sans Font
        run: |
          cd /tmp
          wget https://github.com/mozilla/Fira/archive/4.202.zip
          unzip 4.202.zip
          font_dir="/usr/share/fonts/fira"
          mkdir -p $font_dir
          cp  Fira-4.202/otf/* $font_dir/
          sudo fc-cache -f -v
      - name: Install Fira Mono Font
        run: |
          cd /tmp
          wget https://font.download/dl/font/fira-mono.zip
          unzip fira-mono.zip
          font_dir="/usr/share/fonts/fira-mono"
          mkdir -p $font_dir
          cp *.ttf $font_dir/
          sudo fc-cache -f -v
      - name: Install Libertinus Font
        run: |
          cd /tmp
          wget https://github.com/alerque/libertinus/releases/download/v7.040/Libertinus-7.040.zip
          unzip Libertinus-7.040.zip
          font_dir="/usr/share/fonts/libertinus"
          mkdir -p $font_dir
          cp Libertinus-7.040/static/OTF/* $font_dir/
          sudo fc-cache -f -v

      - name: Install Latex
        run: sudo apt-get install texlive-full texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk texlive-xetex
      - name: Compile
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: Download Artifacts
          path: thesis.pdf
